"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = {
  code: string
  name: string
  nativeName: string
}

type LanguageContextType = {
  currentLanguage: Language
  setLanguage: (language: Language) => void
  languages: Language[]
  translations: Record<string, Record<string, string>>
  t: (key: string) => string
}

const languages: Language[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
]

// Default translations for common UI elements
const translations: Record<string, Record<string, string>> = {
  en: {
    "app.title": "Wildlife AI Tracking and Conservation Hub",
    dashboard: "Dashboard",
    reports: "Reports",
    alerts: "Alerts",
    search: "Search",
    settings: "Settings",
    profile: "Profile",
    analytics: "Analytics",
    "ai.monitoring": "AI Monitoring",
    tracking: "Tracking",
    "animal.care": "Animal Care",
    staff: "Staff",
    database: "Database",
    "settings.appearance": "Appearance",
    "settings.privacy": "Privacy",
    "settings.notifications": "Notifications",
    "settings.language": "Language",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",
    "motion.detected": "Motion Detected!",
    "save.changes": "Save Changes",
    "clear.alerts": "Clear Alerts",
    "action.view": "Action View",
    "drone.response": "Drone Response",
    "anti.poaching": "Anti-Poaching",
    research: "Research",
    "disaster.management": "Disaster Management",
    "logged.in.as": "Logged in as",
    logout: "Logout",
    "hub.name": "Wildlife AI Hub",
    saving: "Saving...",
    Main: "Main",
    Tools: "Tools",
    Advanced: "Advanced",
    Account: "Account",
    "total.animals": "Total Animals",
    "healthy.animals": "Healthy Animals",
    "active.alerts": "Active Alerts",
    "active.now": "Active Now",
    "system.status": "System Status",
    "recent.activity": "Recent Activity",
    "view.analytics": "View Analytics",
    "currently.tracked": "Currently tracked",
    "require.attention": "Require attention",
    "in.field": "In field monitoring",
    "operational": "Operational",
    "connected": "Connected",
    "health.updates": "Health Updates",
    "care.recommendations": "Care Recommendations",
    "veterinary.history": "Veterinary History",
    "health.analytics": "Health Analytics & Trends",
    "monitor.subtitle": "Advanced AI-powered wildlife monitoring and analysis",
    "detection.title": "Wildlife AI Detection",
    "detection.description": "Upload an image or use the camera to identify animals in real-time.",
    "tab.livefeed": "Live Feed",
    "tab.alerts": "Threat Alerts",
    "tab.insights": "Predictive Insights",
    "tab.timeline": "Activity Timeline",
    "field.node": "Live W.A.T.C.H. Field Node",
    "camera.start": "Start Camera",
    "camera.stop": "Stop Camera",
    "detector.label": "Detector",
    "confidence.label": "Confidence",
    "analytics.card.title": "Comprehensive Analytics",
    "analytics.card.subtitle": "View behavioral patterns and health trends",
    "analytics.card.description": "Access detailed behavioral trends analysis, health status distribution, and comprehensive animal health profiles in the dedicated Analytics module.",
    "command.center": "W.A.T.C.H Command Center",
    "system.active": "System Active",
    "monitoring": "Monitoring",
    "actions": "Actions",
    "ai.insights": "AI Insights",
    "operational.status": "Operational Status",
    "drone.missions": "Drone Mission Status",
    "activity.log": "Activity Log",
    "tracking.title": "Wildlife Tracking & Drone Response Command Center",
    "tracking.description": "Monitor wildlife locations and manage autonomous drone response system in real-time",
    "tracking.map.title": "Reserve Tracking Map",
    "simulate.breach": "Simulate Breach",
    "reports.title": "Conservation Reports & Analytics",
    "reports.description": "Generate and view detailed reports on wildlife activity and conservation metrics",
    "animal.care.title": "Animal Care & Health Hub",
    "animal.care.description": "Health monitoring and care recommendations for wildlife",
    "app.ai.monitoring": "AI Monitoring",
    "home.welcome": "Welcome back! You are securely logged in to the conservation network.",
    "home.enter": "Enter Command Center",
    "platforms.badge": "Wildlife Conservation Platform",
    "card.dashboard.title": "Animal Dashboard",
    "card.dashboard.desc": "Monitor animal health, activity, and location in real-time",
    "card.alerts.title": "Smart Alerts",
    "card.alerts.desc": "Get instant notifications for critical wildlife events",
    "card.gps.title": "GPS Tracking",
    "card.gps.desc": "Track animal movements and migration patterns",
    "card.ai.title": "AI Monitoring",
    "card.ai.desc": "AI-powered camera monitoring and behavioral analysis",
    "card.analytics.title": "Analytics",
    "card.analytics.desc": "Comprehensive analytics and conservation insights",
    "card.care.title": "Animal Care",
    "card.care.desc": "Manage health records and veterinary care",
  },
  hi: {
    "app.title": "वन्यजीव AI ट्रैकिंग और संरक्षण हब",
    dashboard: "डैशबोर्ड",
    reports: "रिपोर्ट",
    alerts: "अलर्ट",
    search: "खोज",
    settings: "सेटिंग्स",
    profile: "प्रोफाइल",
    analytics: "एनालिटिक्स",
    "ai.monitoring": "AI निगरानी",
    tracking: "ट्रैकिंग",
    "animal.care": "पशु देखभाल",
    staff: "स्टाफ",
    database: "डेटाबेस",
    "settings.appearance": "उपस्थिति",
    "settings.privacy": "गोपनीयता",
    "settings.notifications": "सूचनाएं",
    "settings.language": "भाषा",
    "theme.light": "हल्का",
    "theme.dark": "गहरा",
    "theme.system": "सिस्टम",
    "motion.detected": "गति का पता चला!",
    "save.changes": "परिवर्तन सहेजें",
    "clear.alerts": "अलर्ट साफ़ करें",
    "action.view": "एक्शन व्यू",
    "drone.response": "ड्रोन रिस्पॉन्स",
    "anti.poaching": "एंटी-पोचिंग",
    research: "अनुसंधान",
    "disaster.management": "आपदा प्रबंधन",
    "logged.in.as": "लॉग इन किया हुआ है",
    logout: "लॉगआउट",
    "hub.name": "वन्यजीव AI हब",
    saving: "सहेज रहा है...",
    Main: "मुख्य",
    Tools: "उपकरण",
    Advanced: "उन्नत",
    Account: "खाता",
    "total.animals": "कुल जानवर",
    "healthy.animals": "स्वस्थ जानवर",
    "active.alerts": "सक्रिय अलर्ट",
    "active.now": "अभी सक्रिय",
    "system.status": "सिस्टम की स्थिति",
    "recent.activity": "हाल की गतिविधि",
    "view.analytics": "एनालिटिक्स देखें",
    "currently.tracked": "वर्तमान में ट्रैक किया गया",
    "require.attention": "ध्यान देने की आवश्यकता है",
    "in.field": "फील्ड निगरानी में",
    "operational": "परिचालन",
    "connected": "जुड़ा हुआ",
    "health.updates": "स्वास्थ्य अपडेट",
    "care.recommendations": "देखभाल के सुझाव",
    "veterinary.history": "पशु चिकित्सा इतिहास",
    "health.analytics": "स्वास्थ्य एनालिटिक्स और रुझान",
    "monitor.subtitle": "उन्नत AI-संचालित वन्यजीव निगरानी और विश्लेषण",
    "detection.title": "वन्यजीव AI पहचान",
    "detection.description": "वास्तविक समय में जानवरों की पहचान करने के लिए एक छवि अपलोड करें या कैमरे का उपयोग करें।",
    "tab.livefeed": "लाइव फीड",
    "tab.alerts": "खतरा अलर्ट",
    "tab.insights": "भविष्य कहनेवाला अंतर्दृष्टि",
    "tab.timeline": "गतिविधि समयरेखा",
    "field.node": "लाइव W.A.T.C.H. फील्ड नोड",
    "camera.start": "कैमरा शुरू करें",
    "camera.stop": "कैमरा बंद करें",
    "detector.label": "डिटेक्टर",
    "confidence.label": "आत्मविश्वास",
    "analytics.card.title": "व्यापक एनालिटिक्स",
    "analytics.card.subtitle": "व्यवहार पैटर्न और स्वास्थ्य रुझान देखें",
    "analytics.card.description": "समर्पित एनालिटिक्स मॉड्यूल में विस्तृत व्यवहार रुझान विश्लेषण, स्वास्थ्य स्थिति वितरण और व्यापक पशु स्वास्थ्य प्रोफाइल तक पहुंचें।",
    "command.center": "W.A.T.C.H कमांड सेंटर",
    "system.active": "सिस्टम सक्रिय है",
    "monitoring": "निगरानी",
    "actions": "कार्रवाई",
    "ai.insights": "AI अंतर्दृष्टि",
    "operational.status": "परिचालन स्थिति",
    "drone.missions": "ड्रोन मिशन स्थिति",
    "activity.log": "गतिविधि लॉग",
    "tracking.title": "वन्यजीव ट्रैकिंग और ड्रोन रिस्पॉन्स कमांड सेंटर",
    "tracking.description": "वास्तविक समय में वन्यजीव स्थानों की निगरानी करें और स्वायत्त ड्रोन प्रतिक्रिया प्रणाली का प्रबंधन करें",
    "tracking.map.title": "रिजर्व ट्रैकिंग मैप",
    "simulate.breach": "सिमुलेट ब्रीच",
    "reports.title": "संरक्षण रिपोर्ट और एनालिटिक्स",
    "reports.description": "वन्यजीव गतिविधि और संरक्षण मेट्रिक्स पर विस्तृत रिपोर्ट तैयार करें और देखें",
    "animal.care.title": "पशु देखभाल और स्वास्थ्य हब",
    "animal.care.description": "वन्यजीवों के लिए स्वास्थ्य निगरानी और देखभाल के सुझाव",
    "app.ai.monitoring": "AI निगरानी",
    "home.welcome": "वापसी पर स्वागत है! आप संरक्षण नेटवर्क में सुरक्षित रूप से लॉग इन हैं।",
    "home.enter": "कमांड सेंटर में प्रवेश करें",
    "platforms.badge": "वन्यजीव संरक्षण मंच",
    "card.dashboard.title": "पशु डैशबोर्ड",
    "card.dashboard.desc": "वास्तविक समय में पशु स्वास्थ्य, गतिविधि और स्थान की निगरानी करें",
    "card.alerts.title": "स्मार्ट अलर्ट",
    "card.alerts.desc": "महत्वपूर्ण वन्यजीव घटनाओं के लिए त्वरित सूचनाएं प्राप्त करें",
    "card.gps.title": "GPS ट्रैकिंग",
    "card.gps.desc": "जानवरों की गतिविधियों और प्रवास पैटर्न को ट्रैक करें",
    "card.ai.title": "AI निगरानी",
    "card.ai.desc": "AI-संचालित कैमरा निगरानी और व्यवहार विश्लेषण",
    "card.analytics.title": "एनालिटिक्स",
    "card.analytics.desc": "व्यापक एनालिटिक्स और संरक्षण अंतर्दृष्टि",
    "card.care.title": "पशु देखभाल",
    "card.care.desc": "स्वास्थ्य रिकॉर्ड और पशु चिकित्सा देखभाल का प्रबंधन करें",
  },
  ta: {
    "app.title": "வனவிலங்கு AI கண்காணிப்பு மற்றும் பாதுகாப்பு மையம்",
    dashboard: "டாஷ்போர்டு",
    reports: "அறிக்கைகள்",
    alerts: "எச்சரிக்கைகள்",
    search: "தேடல்",
    settings: "அமைப்புகள்",
    profile: "சுயவிவரம்",
    analytics: "பகுப்பாய்வு",
    "ai.monitoring": "AI கண்காணிப்பு",
    tracking: "கண்காணிப்பு",
    "animal.care": "விலங்கு பராமரிப்பு",
    staff: "ஊழியர்கள்",
    database: "தரவுத்தளம்",
    "settings.appearance": "தோற்றம்",
    "settings.privacy": "தனியுரிமை",
    "settings.notifications": "அறிவிப்புகள்",
    "settings.language": "மொழி",
    "theme.light": "வெளிச்சம்",
    "theme.dark": "இருள்",
    "theme.system": "கணினி",
    "motion.detected": "அசைவு கண்டறியப்பட்டது!",
    "save.changes": "மாற்றங்களை சேமி",
    "clear.alerts": "எச்சரிக்கைகளை அழி",
    "action.view": "செயல் பார்வை",
    "drone.response": "ட்ரோன் பதில்",
    "anti.poaching": "வேட்டை எதிர்ப்பு",
    research: "ஆராய்ச்சி",
    "disaster.management": "பேரிடர் மேலாண்மை",
    "logged.in.as": "உள்நுழைந்துள்ளீர்கள்",
    logout: "வெளியேறு",
    "hub.name": "விலங்கு AI மையம்",
    saving: "சேமிக்கிறது...",
    Main: "முக்கிய",
    Tools: "கருவிகள்",
    Advanced: "மேம்பட்ட",
    Account: "கணக்கு",
    "total.animals": "மொத்த விலங்குகள்",
    "healthy.animals": "ஆரோக்கியமான விலங்குகள்",
    "active.alerts": "செயலில் உள்ள எச்சரிக்கைகள்",
    "active.now": "இப்போது செயலில்",
    "system.status": "கணினி நிலை",
    "recent.activity": "சமீபத்திய செயல்பாடு",
    "view.analytics": "பகுப்பாய்வைப் பார்க்கவும்",
    "currently.tracked": "தற்போது கண்காணிக்கப்படுகிறது",
    "require.attention": "கவனம் தேவை",
    "in.field": "களக் கண்காணிப்பில்",
    "operational": "செயல்பாட்டில் உள்ளது",
    "connected": "இணைக்கப்பட்டுள்ளது",
    "monitor.subtitle": "மேம்பட்ட AI-இயங்கும் வனவிலங்கு கண்காணிப்பு மற்றும் பகுப்பாய்வு",
    "detection.title": "வனவிலங்கு AI கண்டறிதல்",
    "detection.description": "விலங்குகளை அடையாளம் காண ஒரு படத்தை பதிவேற்றவும் அல்லது கேமராவைப் பயன்படுத்தவும்.",
    "tab.livefeed": "நேரடி ஊட்டம்",
    "tab.alerts": "அச்சுறுத்தல் எச்சரிக்கைகள்",
    "tab.insights": "முன்கணிப்பு நுண்ணறிவு",
    "tab.timeline": "செயல்பாட்டு காலவரிசை",
    "field.node": "நேரடி W.A.T.C.H. கள முனை",
    "camera.start": "கேமராவைத் தொடங்கு",
    "camera.stop": "கேமராவை நிறுத்து",
    "detector.label": "கண்டறிவி",
    "confidence.label": "நம்பிக்கை",
    "analytics.card.title": "விரிவான பகுப்பாய்வு",
    "analytics.card.subtitle": "நடத்தை முறைகள் மற்றும் சுகாதாரப் போக்குகளைக் காண்க",
    "analytics.card.description": "பிரத்யேக பகுப்பாய்வு தொகுதியில் விரிவான நடத்தை போக்குகள் பகுப்பாய்வு மற்றும் விரிவான விலங்கு சுகாதார விவரங்களை அணுகவும்.",
    "command.center": "W.A.T.C.H கட்டளை மையம்",
    "system.active": "அமைப்பு செயலில் உள்ளது",
    "monitoring": "கண்காணிப்பு",
    "actions": "செயல்கள்",
    "ai.insights": "AI நுண்ணறிவு",
    "operational.status": "செயல்பாட்டு நிலை",
    "drone.missions": "ட்ரோன் பணி நிலை",
    "activity.log": "செயல்பாட்டு பதிவு",
    "tracking.title": "வனவிலங்கு கண்காணிப்பு மற்றும் ட்ரோன் பதில் கட்டளை மையம்",
    "tracking.description": "வனவிலங்கு இருப்பிடங்களைக் கண்காணிக்கவும் மற்றும் தன்னாட்சி ட்ரோன் பதில் அமைப்பை நிகழ்நேரத்தில் நிர்வகிக்கவும்",
    "tracking.map.title": "ரிசர்வ் கண்காணிப்பு வரைபடம்",
    "simulate.breach": "மீறலை உருவகப்படுத்து",
    "reports.title": "பாதுகாப்பு அறிக்கைகள் மற்றும் பகுப்பாய்வு",
    "reports.description": "வனவிலங்கு செயல்பாடு மற்றும் பாதுகாப்பு அளவீடுகள் குறித்த விரிவான அறிக்கைகளை உருவாக்கி பார்க்கவும்",
    "animal.care.title": "விலங்கு பராமரிப்பு மற்றும் சுகாதார மையம்",
    "animal.care.description": "வனவிலங்குகளுக்கான சுகாதார கண்காணிப்பு மற்றும் பராமரிப்பு பரிந்துரைகள்",
    "app.ai.monitoring": "AI கண்காணிப்பு",
  },
  te: {
    "app.title": "వన్యప్రాణి AI ట్రాకింగ్ మరియు కన్జర్వేషన్ హబ్",
    dashboard: "డాష్‌బోర్డ్",
    reports: "నివేదికలు",
    alerts: "హెచ్చరికలు",
    search: "శోధన",
    settings: "సెట్టింగ్‌లు",
    profile: "ప్రొఫైల్",
    analytics: "విశ్లేషణలు",
    "ai.monitoring": "AI పర్యవేక్షణ",
    "command.center": "W.A.T.C.H కమాండ్ సెంటర్",
    "system.active": "సిస్టమ్ పనిచేస్తోంది",
    monitoring: "పర్యవేక్షణ",
    actions: "చర్యలు",
    "ai.insights": "AI అంతర్దృష్తులు",
    "operational.status": "కార్యాచరణ స్థితి",
    "drone.missions": "డ్రోన్ మిషన్ స్థితి",
    "activity.log": "కార్యాచరణ లాగ్",
    tracking: "ట్రాకింగ్",
    "animal.care": "జంతు సంరక్షణ",
    staff: "సిబ్బంది",
    database: "డేటాబేస్",
    "settings.appearance": "రూపం",
    "settings.privacy": "గోప్యత",
    "settings.notifications": "నోటిఫికేషన్లు",
    "settings.language": "భాష",
    "theme.light": "లైట్",
    "theme.dark": "డార్క్",
    "theme.system": "సిస్టమ్",
    "motion.detected": "కదలిక గుర్తించబడింది!",
    "save.changes": "మార్పులను సేవ్ చేయండి",
    "clear.alerts": "హెచ్చరికలను క్లియర్ చేయండి",
    "action.view": "యాక్షన్ వ్యూ",
    "drone.response": "డ్రోన్ స్పందన",
    "anti.poaching": "యాంటీ పోచింగ్",
    research: "పరిశోధన",
    "disaster.management": "విపత్తు నిర్వహణ",
    "logged.in.as": "లాగిన్ అయ్యారు",
    logout: "లాగ్ అవుట్",
    "hub.name": "వన్యప్రాణి AI హబ్",
    saving: "సేవ్ అవుతోంది...",
    Main: "ప్రధాన",
    Tools: "ఉపకరణాలు",
    Advanced: "అధునాతన",
    Account: "ఖాతా",
    "total.animals": "మొత్తం జంతువులు",
    "healthy.animals": "ఆరోగ్యకరమైన జంతువులు",
    "active.alerts": "క్రియాశీల హెచ్చరికలు",
    "active.now": "ప్రస్తుతం పనిచేస్తున్నారు",
    "system.status": "సిస్టమ్ స్థితి",
    "recent.activity": "ఇటీవలి కార్యాచరణ",
    "view.analytics": "విశ్లేషణలను వీక్షించండి",
    "currently.tracked": "ప్రస్తుతం ట్రాక్ చేయబడింది",
    "require.attention": "శ్రద్ధ అవసరం",
    "in.field": "ఫీల్డ్ పర్యవేక్షణలో",
    "operational": "పనిచేస్తోంది",
    "connected": "కనెక్ట్ చేయబడింది",
    "monitor.subtitle": "అధునాతన AI-ఆధారిత వన్యప్రాణి పర్యవేక్షణ మరియు విశ్లేషణ",
    "detection.title": "వన్యప్రాణి AI గుర్తింపు",
    "detection.description": "జంతువులను నిజ సమయంలో గుర్తించడానికి చిత్రాన్ని అప్‌లోడ్ చేయండి లేదా కెమెరాను ఉపయోగించండి.",
    "tab.livefeed": "లైవ్ ఫీడ్",
    "tab.alerts": "ముప్పు హెచ్చరికలు",
    "tab.insights": "అంచనా అంతర్దృష్టులు",
    "tab.timeline": "కార్యాచరణ కాలక్రమం",
    "field.node": "లైవ్ W.A.T.C.H. ఫీల్డ్ నోడ్",
    "camera.start": "కెమెరాను ప్రారంభించండి",
    "camera.stop": "కెమెరాను ఆపండి",
    "detector.label": "డిటెక్టర్",
    "confidence.label": "నమ్మకం",
    "analytics.card.title": "సమగ్ర విశ్లేషణలు",
    "analytics.card.subtitle": "ప్రవర్తనా నమూనాలు మరియు ఆరోగ్య పోకడలను వీక్షించండి",
    "analytics.card.description": "అంకితమైన అనలిటిక్స్ మాడ్యూల్‌లో వివరణాత్మక ప్రవర్తనా ధోరణుల విశ్లేషణ మరియు సమగ్ర జంతు ఆరోగ్య ప్రొఫైల్‌లను యాక్సెస్ చేయండి.",
  },
  kn: {
    "app.title": "ವನ್ಯಜೀವಿ AI ಟ್ರ್ಯಾಕಿಂಗ್ ಮತ್ತು ಸಂರಕ್ಷಣಾ ಕೇಂದ್ರ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    reports: "ವರದಿಗಳು",
    alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    search: "ಹುಡುಕಿ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    analytics: "ವಿಶ್ಲೇಷಣೆಗಳು",
    "ai.monitoring": "AI ಮೇಲ್ವಿಚಾರಣೆ",
    tracking: "ಟ್ರ್ಯಾಕಿಂಗ್",
    "animal.care": "ಪ್ರಾಣಿ ಆರೈಕೆ",
    staff: "ಸಿಬ್ಬಂದಿ",
    database: "ಡೇಟಾಬೇಸ್",
    "settings.appearance": "ರೂಪ",
    "settings.privacy": "ಗೌಪ್ಯತೆ",
    "settings.notifications": "ಅಧಿಸೂಚನೆಗಳು",
    "settings.language": "ಭಾಷೆ",
    "theme.light": "ಬೆಳಕು",
    "theme.dark": "ಕತ್ತಲೆ",
    "theme.system": "ಸಿಸ್ಟಮ್",
    "motion.detected": "ಚಲನೆ ಪತ್ತೆಯಾಗಿದೆ!",
    "save.changes": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    "clear.alerts": "ಎಚ್ಚರಿಕೆಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ",
    "action.view": "ಆಕ್ಷನ್ ವ್ಯೂ",
    "drone.response": "ಡ್ರೋನ್ ಪ್ರತಿಕ್ರಿಯೆ",
    "anti.poaching": "ಬೇಟೆ ತಡೆ",
    research: "ಸಂಶೋಧನೆ",
    "disaster.management": "ವಿಪತ್ತು ನಿರ್ವಹಣೆ",
    "logged.in.as": "ಲಾಗಿನ್ ಆಗಿದ್ದೀರಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    "hub.name": "ವನ್ಯಜೀವಿ AI ಕೇಂದ್ರ",
    saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    Main: "ಮುಖ್ಯ",
    Tools: "ಪರಿಕರಗಳು",
    Advanced: "ಸುಧಾರಿತ",
    Account: "ಖಾತೆ",
  },
  mr: {
    "app.title": "वन्यजीव AI ट्रॅकिंग आणि संवर्धन केंद्र",
    dashboard: "डॅशबोर्ड",
    reports: "अहवाल",
    alerts: "सूचना",
    search: "शोध",
    settings: "सेटिंग्ज",
    profile: "प्रोफाइल",
    analytics: "विश्लेषण",
    "ai.monitoring": "AI निरीक्षण",
    tracking: "ट्रॅकिंग",
    "animal.care": "प्राणी काळजी",
    staff: "कर्मचारी",
    database: "डेटाबेस",
    "settings.appearance": "दिसणे",
    "settings.privacy": "गोपनीयता",
    "settings.notifications": "सूचना",
    "settings.language": "भाषा",
    "theme.light": "प्रकाश",
    "theme.dark": "गडद",
    "theme.system": "सिस्टम",
    "motion.detected": "हालचाल आढळली!",
    "save.changes": "बदल जतन करा",
    "clear.alerts": "सूचना साफ करा",
    "action.view": "ॲक्शन व्ह्यू",
    "drone.response": "ड्रोन प्रतिसाद",
    "anti.poaching": "एंटी-पोचिंग",
    research: "संशोधन",
    "disaster.management": "आपत्ती व्यवस्थापन",
    "logged.in.as": "लॉग इन केले आहे",
    logout: "लॉगआउट",
    "hub.name": "वन्यजीव AI हब",
    saving: "जतन करत आहे...",
    Main: "मुख्य",
    Tools: "साधने",
    Advanced: "प्रगत",
    Account: "खाते",
  },
  ur: {
    "app.title": "جنگلی حیات AI ٹریکنگ اور تحفظ مرکز",
    dashboard: "ڈیش بورڈ",
    reports: "رپورٹس",
    alerts: "الرٹس",
    search: "تلاش",
    settings: "ترتیبات",
    profile: "پروفائل",
    analytics: "تجزیات",
    "ai.monitoring": "AI نگرانی",
    tracking: "ٹریکنگ",
    "animal.care": "جانوروں کی دیکھ بھال",
    staff: "عملہ",
    database: "ڈیٹا بیس",
    "settings.appearance": "ظاہری شکل",
    "settings.privacy": "رازداری",
    "settings.notifications": "اطلاعات",
    "settings.language": "زبان",
    "theme.light": "روشن",
    "theme.dark": "تاریک",
    "theme.system": "سسٹم",
    "motion.detected": "حرکت کا پتہ چلا!",
    "save.changes": "تبدیلیاں محفوظ کریں",
    "clear.alerts": "الرٹس صاف کریں",
    "action.view": "ایکشن ویو",
    "drone.response": "ڈرون جواب",
    "anti.poaching": "اینٹی پوچنگ",
    research: "تحقیق",
    "disaster.management": "ڈیزاسٹر مینजمنٹ",
    "logged.in.as": "لاگ ان ہیں",
    logout: "لاگ آؤٹ",
    "hub.name": "وائلڈ لائف AI حب",
    saving: "محفوظ ہو رہا ہے...",
    Main: "مین",
    Tools: "ٹولز",
    Advanced: "ایڈوانસڈ",
    Account: "اکاؤنٹ",
  },
  bn: {
    "app.title": "বন্যপ্রাণী AI ট্র্যাকিং এবং সংরক্ষণ কেন্দ্র",
    dashboard: "ড্যাশবোর্ড",
    reports: "রিপোর্ট",
    alerts: "সতর্কতা",
    search: "অনুসন্ধান",
    settings: "সেটিংস",
    profile: "প্রোফাইল",
    analytics: "বিশ্লেষণ",
    "ai.monitoring": "AI পর্যবেক্ষণ",
    tracking: "ট্র্যাকিং",
    "animal.care": "প্রাণী যত্ন",
    staff: "কর্মচারী",
    database: "ডাটাবেস",
    "settings.appearance": "চেহারা",
    "settings.privacy": "গোপনীয়তা",
    "settings.notifications": "বিজ্ঞপ্তি",
    "settings.language": "ভাষা",
    "theme.light": "হালকা",
    "theme.dark": "গাঢ়",
    "theme.system": "সিস্টেম",
    "motion.detected": "গতি সনাক্ত হয়েছে!",
    "save.changes": "পরিবর্তনগুলি সংরক্ষণ করুন",
    "clear.alerts": "সতর্কতা মুছুন",
    "action.view": "অ্যাকশন ভিউ",
    "drone.response": "ড্রोन প্রতিক্রিয়া",
    "anti.poaching": "চোরাশিকার বিরোধী",
    research: "গবেষণা",
    "disaster.management": "দুর্যোগ ব্যবস্থাপনা",
    "logged.in.as": "লগ ইন করা হয়েছে",
    logout: "লগআউট",
    "hub.name": "বন্যপ্রাণী AI হাব",
    saving: "সংরক্ষণ করা হচ্ছে...",
    Main: "মূল",
    Tools: "সরঞ্জাম",
    Advanced: "উন্নত",
    Account: "অ্যাকাউন্ট",
  },
  gu: {
    "app.title": "વન્યજીવન AI ટ્રેકિંગ અને સંરક્ષણ કેન્દ્ર",
    dashboard: "ડેશબોર્ડ",
    reports: "રિપોર્ટ્સ",
    alerts: "એલર્ટ્સ",
    search: "શોધ",
    settings: "સેટિંગ્સ",
    profile: "પ્રોફાઇલ",
    analytics: "એનાલિટિક્સ",
    "ai.monitoring": "AI મોનિટરિંગ",
    tracking: "ટ્રેકિંગ",
    "animal.care": "પ્રાણી સંભાળ",
    staff: "સ્ટાફ",
    database: "ડેટાબેઝ",
    "settings.appearance": "દેખાવ",
    "settings.privacy": "ગોપનીયતા",
    "settings.notifications": "સૂચનાઓ",
    "settings.language": "ભાષા",
    "theme.light": "પ્રકાશ",
    "theme.dark": "અંધારું",
    "theme.system": "સિસ્ટમ",
    "motion.detected": "ગતિ શોધાઈ!",
    "save.changes": "ફેરફારો સાચવો",
    "clear.alerts": "એલર્ટ્સ સાફ કરો",
    "action.view": "એક્શન વ્યૂ",
    "drone.response": "ડ્રોન પ્રતિસાદ",
    "anti.poaching": "એન્ટી-પોચિંગ",
    research: "સંશોધન",
    "disaster.management": "આપત્તિ વ્યવસ્થાપન",
    "logged.in.as": "લોગ ઇન કરેલ છે",
    logout: "લોગઆઉટ",
    "hub.name": "વન્યજીવન AI હબ",
    saving: "સાચવી રહ્યું છે...",
    Main: "મુખ્ય",
    Tools: "સાધનો",
    Advanced: "અદ્યતન",
    Account: "ખાતું",
  },
  ml: {
    "app.title": "വന്യജീവി AI ട്രാക്കിംഗ് ആൻడ్ കൺസർവേഷൻ హబ్",
    dashboard: "ഡാഷ്ബോർഡ്",
    reports: "റിപ്പോർട്ടുകൾ",
    alerts: "അലേർട്ടുകൾ",
    search: "തിരയൽ",
    settings: "ക്രമീകരണങ്ങൾ",
    profile: "പ്രൊഫൈൽ",
    analytics: "അനലിറ്റിക്സ്",
    "ai.monitoring": "AI നിരീക്ഷണം",
    tracking: "ട്രാക്കിംഗ്",
    "animal.care": "മൃഗ പരിപാലനം",
    staff: "ജീവനക്കാർ",
    database: "ഡാറ്റാബേസ്",
    "settings.appearance": "രൂപം",
    "settings.privacy": "സ്വകാര്യത",
    "settings.notifications": "അറിയിപ്പുകൾ",
    "settings.language": "ഭാഷ",
    "theme.light": "വെളിച്ചം",
    "theme.dark": "ഇരുട്ട്",
    "theme.system": "സിസ്റ്റം",
    "motion.detected": "ചലനം കണ്ടെത്തി!",
    "save.changes": "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",
    "clear.alerts": "അലേർട്ടുകൾ മായ്ക്കുക",
    "action.view": "ആക്ഷൻ വ്യൂ",
    "drone.response": "ഡ്രോൺ പ്രതികരണം",
    "anti.poaching": "വേട്ടയാടൽ വിരുദ്ധം",
    research: "ഗവേഷണം",
    "disaster.management": "ദുരന്ത നിവാരണം",
    "logged.in.as": "ലോഗിൻ ചെയ്തിരിക്കുന്നു",
    logout: "ലോഗൗട്ട്",
    "hub.name": "വന്യജീവി AI ഹബ്",
    saving: "സംരക്ഷിക്കുന്നു...",
    Main: "ಪ್ರಧാനം",
    Tools: "ഉപകരണങ്ങൾ",
    Advanced: "അഡ്വാൻസ്ഡ്",
    Account: "അക്കൗണ്ട്",
  },
}

const defaultLanguage = languages[0]

const LanguageContext = createContext<LanguageContextType>({
  currentLanguage: defaultLanguage,
  setLanguage: () => {},
  languages,
  translations,
  t: (key: string) => key,
})

export const useLanguage = () => useContext(LanguageContext)

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(defaultLanguage)

  // Load saved language preference from localStorage on component mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language")
    if (savedLanguage) {
      const language = languages.find((lang) => lang.code === savedLanguage)
      if (language) {
        setCurrentLanguage(language)
      }
    }
  }, [])

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language)
    localStorage.setItem("language", language.code)
    // Update HTML lang attribute
    document.documentElement.lang = language.code
    // For RTL languages like Urdu
    document.documentElement.dir = language.code === "ur" ? "rtl" : "ltr"
  }

  // Translation function
  const t = (key: string): string => {
    const langTranslations = translations[currentLanguage.code]
    return langTranslations && langTranslations[key] ? langTranslations[key] : key
  }

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, languages, translations, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
